---
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-private-key
    - id: end-of-file-fixer
- repo: https://github.com/adrienverge/yamllint
  rev: v1.21.0
  hooks:
    - id: yamllint
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.23.2
  hooks:
    - id: markdownlint
      exclude: (docker/README.md|CHANGELOG.md)
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
    - id: commitizen
      stages: [commit-msg]
