---
# tasks file for docker
# apt_key needs this
- name: Install apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: present
  tags: docker

- name: Add repository gpg key by key url
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    id: 0EBFCD88
  tags: docker

- name: Create docker configuration directory
  become: true
  file:
    path: /etc/docker
    owner: root
    group: root
    state: directory
    mode: 0755
  tags: docker

- name: Add docker configuration
  become: true
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags: docker

- name: Add docker repository
  become: true
  apt_repository:
    repo: deb [arch={{ docker_architecture }}] https://download.docker.com/linux/debian
      stretch stable
    state: present
    update_cache: true
    mode: 0644
  tags: docker

- name: Install docker
  become: true
  apt:
    name: docker-ce
    state: present
    update_cache: true
    cache_valid_time: 0
  tags: docker

- name: Install docker and docker-compose pip package
  become: true
  pip:
    name: '{{ item }}'
  loop:
    - docker
    - docker-compose
  when: install_docker_pip
  tags: docker

- name: Configure crontab to clean up docker garbage
  become: true
  cron:
    minute: '0'
    hour: '*/4'
    job: docker system prune -f -a 2>&1 | /usr/bin/logger -t docker-garbage-collector
    state: present
    name: docker-garbage-collector
