---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

lint:
  name: yamllint

platforms:
  - name: docker-ubuntu-18.04
    box: generic/ubuntu1804
    memory: 2048
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
    instance_raw_config_args:
      #  - "vm.network 'forwarded_port', guest: 80, host: 8181"
      - "vm.synced_folder './', '/vagrant'"
  - name: docker-ubuntu-20.04
    box: generic/ubuntu2004
    memory: 2048
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
    instance_raw_config_args:
      #  - "vm.network 'forwarded_port', guest: 80, host: 8181"
      - "vm.synced_folder './', '/vagrant'"

provisioner:
  name: ansible
  playbooks:
    converge: ../playbook.yml
    prepare: ../prepare.yml
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  directory: ../tests/
  lint:
    name: flake8
